version: '2.2'
services:
  stabbot:
    build: .
    volumes:
     - ./data:/bot/data
    cpu_count: 1
    mem_limit: 3G
    environment:
      - DEBUG=False
      - DRYRUN=False
      - INCLUDE_OLD_MENTIONS=False