version: '2.2'
services:
  colorbot:
    build: .
    volumes:
     - ./data:/bot/data
    cpu_count: 1
    mem_limit: 3G
    environment:
      - DEBUG=False
      - DRYRUN=False
      - INCLUDE_OLD_MENTIONS=False
    restart: always

  redis:
    image: redis
    volumes:
     - ./data/redis:/data
    expose:
     - 6379
    restart: always
